from __future__ import annotations

from app.models import (
    ConnectorStatus,
    Entity,
    HistoricalPoint,
    InsightNote,
    Relationship,
    Snapshot,
)


def _entity(
    entity_id: str,
    name: str,
    kind: str,
    source: str,
    environment: str,
    description: str,
    *,
    criticality: int = 1,
    risk_score: int = 0,
    tags: list[str] | None = None,
    owner: str | None = None,
) -> Entity:
    return Entity(
        id=entity_id,
        name=name,
        kind=kind,
        source=source,
        environment=environment,
        description=description,
        criticality=criticality,
        risk_score=risk_score,
        tags=tags or [],
        owner=owner,
    )


def _relationship(
    rel_id: str,
    kind: str,
    source: str,
    target: str,
    label: str,
    rationale: str,
    *,
    permissions: list[str] | None = None,
    inherits: bool = False,
    temporary: bool = False,
    expires_at: str | None = None,
    removable: bool = False,
    metadata: dict[str, str] | None = None,
) -> Relationship:
    return Relationship(
        id=rel_id,
        kind=kind,
        source=source,
        target=target,
        label=label,
        rationale=rationale,
        permissions=permissions or [],
        inherits=inherits,
        temporary=temporary,
        expires_at=expires_at,
        removable=removable,
        metadata=metadata or {},
    )


def build_demo_snapshot() -> Snapshot:
    entities = [
        _entity(
            "user_alice",
            "Alice Wong",
            "user",
            "Active Directory",
            "hybrid",
            "Finance analyst who works on payroll close and reporting.",
            criticality=2,
            risk_score=38,
            tags=["finance", "employee"],
            owner="Finance IT",
        ),
        _entity(
            "user_bruno",
            "Bruno Rossi",
            "user",
            "Entra ID",
            "hybrid",
            "Payroll operations lead responsible for mailbox-driven approvals.",
            criticality=3,
            risk_score=52,
            tags=["payroll", "approver"],
            owner="Payroll Ops",
        ),
        _entity(
            "user_nadia",
            "Nadia Khan",
            "user",
            "Entra ID",
            "cloud",
            "Cloud platform engineer with production deployment responsibility.",
            criticality=4,
            risk_score=72,
            tags=["cloud", "platform"],
            owner="Platform Engineering",
        ),
        _entity(
            "user_mila",
            "Mila Chen",
            "user",
            "Entra ID",
            "cloud",
            "Security operations delegate with directory-wide read visibility.",
            criticality=4,
            risk_score=68,
            tags=["secops", "delegate"],
            owner="Security",
        ),
        _entity(
            "user_omar",
            "Omar Diaz",
            "user",
            "Okta",
            "cloud",
            "External payroll auditor with time-bound delegated access.",
            criticality=3,
            risk_score=71,
            tags=["external", "auditor"],
            owner="Third-party Governance",
        ),
        _entity(
            "user_paolo",
            "Paolo Greco",
            "user",
            "Active Directory",
            "on-prem",
            "IT support engineer with narrow file-share exception and delegated read role.",
            criticality=2,
            risk_score=44,
            tags=["support", "operations"],
            owner="IT Support",
        ),
        _entity(
            "user_lena",
            "Lena Petrov",
            "user",
            "CyberArk",
            "hybrid",
            "Break-glass operator used during production incidents.",
            criticality=5,
            risk_score=84,
            tags=["pam", "emergency"],
            owner="Privileged Access",
        ),
        _entity(
            "svc_finops",
            "svc-finops-automation",
            "service_account",
            "Azure Managed Identity",
            "cloud",
            "Automation identity that rotates and exports payroll-related secrets.",
            criticality=4,
            risk_score=63,
            tags=["service-account", "automation"],
            owner="FinOps",
        ),
        _entity(
            "grp_all_employees",
            "All Employees",
            "group",
            "Active Directory",
            "on-prem",
            "Baseline employee group synced from HR.",
            criticality=1,
            risk_score=5,
            tags=["baseline"],
        ),
        _entity(
            "grp_finance_analysts",
            "Finance Analysts",
            "group",
            "Active Directory",
            "hybrid",
            "Finance analyst cohort synchronized to SharePoint and Windows ACLs.",
            criticality=2,
            risk_score=26,
            tags=["finance", "group"],
        ),
        _entity(
            "grp_payroll_ops",
            "Payroll Ops",
            "group",
            "Entra ID",
            "hybrid",
            "Operational payroll team with mailbox and folder processing rights.",
            criticality=3,
            risk_score=44,
            tags=["payroll", "group"],
        ),
        _entity(
            "grp_payroll_editors",
            "Payroll Editors",
            "group",
            "Active Directory",
            "hybrid",
            "Aggregated entitlement group used to drive folder and SharePoint access.",
            criticality=4,
            risk_score=63,
            tags=["entitlement", "aggregation"],
        ),
        _entity(
            "grp_azure_prod_owners",
            "Azure Prod Owners",
            "group",
            "Entra ID",
            "cloud",
            "Production platform owners for the payroll Azure subscription.",
            criticality=5,
            risk_score=82,
            tags=["cloud", "privileged"],
        ),
        _entity(
            "grp_secops_delegates",
            "SecOps Delegates",
            "group",
            "Entra ID",
            "cloud",
            "Security delegates with read-only directory scope for investigations.",
            criticality=3,
            risk_score=48,
            tags=["secops", "delegated-admin"],
        ),
        _entity(
            "grp_external_auditors",
            "External Auditors",
            "group",
            "Okta",
            "cloud",
            "Guest population used for quarterly payroll evidence reviews.",
            criticality=3,
            risk_score=57,
            tags=["external", "guest"],
        ),
        _entity(
            "grp_break_glass",
            "Break Glass Responders",
            "group",
            "CyberArk",
            "hybrid",
            "Emergency responders allowed to recover cloud secrets during outages.",
            criticality=5,
            risk_score=86,
            tags=["emergency", "privileged"],
        ),
        _entity(
            "role_windows_file_modify",
            "Windows File Modify",
            "role",
            "Windows ACL Policy",
            "on-prem",
            "Role that maps to modify rights on the finance share and descendants.",
            criticality=3,
            risk_score=41,
            tags=["acl", "filesystem"],
        ),
        _entity(
            "role_sharepoint_editor",
            "SharePoint Payroll Editor",
            "role",
            "Microsoft 365",
            "cloud",
            "Role that grants edit rights on the payroll collaboration site.",
            criticality=3,
            risk_score=39,
            tags=["m365", "sharepoint"],
        ),
        _entity(
            "role_m365_mailbox_full",
            "Payroll Mailbox Full Access",
            "role",
            "Exchange Online",
            "cloud",
            "Role that grants full mailbox access for payroll approvals.",
            criticality=4,
            risk_score=66,
            tags=["m365", "mailbox"],
        ),
        _entity(
            "role_azure_contributor",
            "Azure Subscription Contributor",
            "role",
            "Azure RBAC",
            "cloud",
            "Role that grants deployment and write permissions at subscription scope.",
            criticality=5,
            risk_score=77,
            tags=["azure", "rbac", "privileged"],
        ),
        _entity(
            "role_keyvault_secrets",
            "Key Vault Secrets Officer",
            "role",
            "Azure RBAC",
            "cloud",
            "Role that grants secret read, write and delete at Key Vault scope.",
            criticality=5,
            risk_score=79,
            tags=["azure", "secrets", "privileged"],
        ),
        _entity(
            "role_global_reader",
            "Global Directory Reader",
            "role",
            "Entra ID",
            "cloud",
            "Read-only directory role used for investigation and support flows.",
            criticality=3,
            risk_score=51,
            tags=["entra", "directory"],
        ),
        _entity(
            "res_share_finance",
            "Finance Share",
            "resource",
            "Windows File Server",
            "on-prem",
            "On-premises finance share hosting close documents and payroll exports.",
            criticality=4,
            risk_score=75,
            tags=["filesystem", "critical"],
            owner="Finance Operations",
        ),
        _entity(
            "res_folder_payroll",
            "Payroll Folder",
            "resource",
            "Windows File Server",
            "on-prem",
            "Restricted payroll folder containing salary exports and approvals.",
            criticality=5,
            risk_score=90,
            tags=["filesystem", "payroll", "critical"],
            owner="Payroll Ops",
        ),
        _entity(
            "res_sharepoint_payroll",
            "Payroll Collaboration Site",
            "resource",
            "SharePoint Online",
            "cloud",
            "SharePoint site used to coordinate payroll runs and approvals.",
            criticality=4,
            risk_score=67,
            tags=["sharepoint", "collaboration"],
            owner="Payroll Ops",
        ),
        _entity(
            "res_mailbox_payroll",
            "payroll-ops@northwind.example",
            "resource",
            "Exchange Online",
            "cloud",
            "Shared mailbox used for payroll change requests and manager approvals.",
            criticality=4,
            risk_score=70,
            tags=["mailbox", "m365"],
            owner="Payroll Ops",
        ),
        _entity(
            "res_azure_prod_subscription",
            "Azure Subscription: Payroll-Prod",
            "resource",
            "Azure",
            "cloud",
            "Production subscription hosting payroll APIs, storage and Key Vault.",
            criticality=5,
            risk_score=92,
            tags=["azure", "subscription", "critical"],
            owner="Platform Engineering",
        ),
        _entity(
            "res_keyvault_payroll",
            "kv-payroll-prod",
            "resource",
            "Azure Key Vault",
            "cloud",
            "Key Vault that stores tokens and signing secrets for payroll integrations.",
            criticality=5,
            risk_score=96,
            tags=["azure", "keyvault", "secret"],
            owner="Platform Engineering",
        ),
        _entity(
            "res_secret_salary_export",
            "secret://salary-export-token",
            "resource",
            "Azure Key Vault",
            "cloud",
            "Secret used by batch jobs to export salary data to downstream systems.",
            criticality=5,
            risk_score=97,
            tags=["azure", "secret", "token"],
            owner="FinOps",
        ),
        _entity(
            "res_global_directory",
            "Entra Global Directory",
            "resource",
            "Microsoft Entra ID",
            "cloud",
            "Tenant-wide directory object graph used during investigations and support.",
            criticality=4,
            risk_score=64,
            tags=["entra", "directory"],
            owner="Identity Governance",
        ),
    ]

    relationships = [
        _relationship(
            "rel_user_alice_finance",
            "member_of",
            "user_alice",
            "grp_finance_analysts",
            "Member of Finance Analysts",
            "Alice is synchronized from HR into the Finance Analysts group.",
            removable=True,
        ),
        _relationship(
            "rel_user_bruno_payroll_ops",
            "member_of",
            "user_bruno",
            "grp_payroll_ops",
            "Member of Payroll Ops",
            "Bruno is a core payroll operator and inherits the team's entitlements.",
        ),
        _relationship(
            "rel_user_nadia_azure_prod_owners",
            "member_of",
            "user_nadia",
            "grp_azure_prod_owners",
            "Member of Azure Prod Owners",
            "Nadia belongs to the platform owners group for production.",
        ),
        _relationship(
            "rel_user_mila_secops_delegates",
            "member_of",
            "user_mila",
            "grp_secops_delegates",
            "Member of SecOps Delegates",
            "Mila is part of the security delegation group used for investigations.",
        ),
        _relationship(
            "rel_user_omar_external_auditors",
            "member_of",
            "user_omar",
            "grp_external_auditors",
            "Member of External Auditors",
            "Omar is onboarded as a guest into the external auditors group.",
        ),
        _relationship(
            "rel_user_paolo_all_employees",
            "member_of",
            "user_paolo",
            "grp_all_employees",
            "Member of All Employees",
            "Paolo receives the standard baseline identity footprint.",
        ),
        _relationship(
            "rel_user_lena_break_glass",
            "member_of",
            "user_lena",
            "grp_break_glass",
            "Member of Break Glass Responders",
            "Lena is in the emergency responders vault.",
        ),
        _relationship(
            "rel_finance_into_payroll_editors",
            "nested_group",
            "grp_finance_analysts",
            "grp_payroll_editors",
            "Finance Analysts nested into Payroll Editors",
            "Finance analysts are funneled through a shared entitlement group to simplify ACLs.",
            removable=True,
        ),
        _relationship(
            "rel_payroll_ops_into_payroll_editors",
            "nested_group",
            "grp_payroll_ops",
            "grp_payroll_editors",
            "Payroll Ops nested into Payroll Editors",
            "Payroll operators inherit the same edit surface used by analysts.",
        ),
        _relationship(
            "rel_break_glass_into_azure_prod_owners",
            "nested_group",
            "grp_break_glass",
            "grp_azure_prod_owners",
            "Break Glass Responders nested into Azure Prod Owners",
            "Emergency responders inherit production owner rights during outage recovery.",
            removable=True,
        ),
        _relationship(
            "rel_delegate_omar_payroll_editors",
            "delegated_access",
            "user_omar",
            "grp_payroll_editors",
            "Temporary delegation to Payroll Editors",
            "Omar received a temporary delegated membership to review payroll process evidence.",
            temporary=True,
            expires_at="2026-03-31T23:59:00Z",
            removable=True,
        ),
        _relationship(
            "rel_delegate_paolo_global_reader",
            "delegated_access",
            "user_paolo",
            "role_global_reader",
            "Temporary delegation to Global Directory Reader",
            "Support can self-serve read-only directory visibility during incidents.",
            temporary=True,
            expires_at="2026-03-22T18:00:00Z",
            removable=True,
        ),
        _relationship(
            "rel_payroll_editors_windows_modify",
            "assigned_role",
            "grp_payroll_editors",
            "role_windows_file_modify",
            "Payroll Editors assigned Windows File Modify",
            "The aggregated payroll entitlement group is bound to the file modify role.",
        ),
        _relationship(
            "rel_payroll_editors_sharepoint_editor",
            "assigned_role",
            "grp_payroll_editors",
            "role_sharepoint_editor",
            "Payroll Editors assigned SharePoint Payroll Editor",
            "The same group drives collaboration access for payroll workflows.",
        ),
        _relationship(
            "rel_payroll_ops_mailbox_full",
            "assigned_role",
            "grp_payroll_ops",
            "role_m365_mailbox_full",
            "Payroll Ops assigned mailbox full access role",
            "Mailbox access is granted through the operational payroll group.",
        ),
        _relationship(
            "rel_azure_prod_owners_contributor",
            "assigned_role",
            "grp_azure_prod_owners",
            "role_azure_contributor",
            "Azure Prod Owners assigned Subscription Contributor",
            "Production owners receive contributor rights at subscription scope.",
            removable=True,
        ),
        _relationship(
            "rel_secops_delegates_global_reader",
            "assigned_role",
            "grp_secops_delegates",
            "role_global_reader",
            "SecOps Delegates assigned Global Directory Reader",
            "Security delegates receive tenant-wide read visibility to investigate alerts.",
        ),
        _relationship(
            "rel_svc_finops_keyvault_officer",
            "assigned_role",
            "svc_finops",
            "role_keyvault_secrets",
            "Automation assigned Key Vault Secrets Officer",
            "FinOps automation rotates and reads payroll secrets directly.",
        ),
        _relationship(
            "rel_break_glass_keyvault_officer",
            "assigned_role",
            "grp_break_glass",
            "role_keyvault_secrets",
            "Break Glass Responders assigned Key Vault Secrets Officer",
            "Emergency responders can recover secrets when automation is unavailable.",
        ),
        _relationship(
            "rel_external_auditors_sharepoint_read",
            "direct_acl",
            "grp_external_auditors",
            "res_sharepoint_payroll",
            "Direct SharePoint read ACL",
            "Guest auditors are granted direct read access to the payroll collaboration site.",
            permissions=["Read"],
        ),
        _relationship(
            "rel_paolo_finance_share_read",
            "direct_acl",
            "user_paolo",
            "res_share_finance",
            "Direct read exception on Finance Share",
            "IT support has a narrow direct exception to inspect file-share health.",
            permissions=["Read"],
            removable=True,
        ),
        _relationship(
            "rel_alice_mailbox_read",
            "direct_acl",
            "user_alice",
            "res_mailbox_payroll",
            "Direct read exception on payroll mailbox",
            "Alice can read the mailbox during payroll close through a ticketed exception.",
            permissions=["Read"],
            temporary=True,
            expires_at="2026-03-20T20:00:00Z",
            removable=True,
        ),
        _relationship(
            "rel_windows_modify_finance_share",
            "role_grant",
            "role_windows_file_modify",
            "res_share_finance",
            "Modify on Finance Share and descendants",
            "The file modify role grants read, write and delete on the share and all child folders.",
            permissions=["Read", "Write", "Delete"],
            inherits=True,
        ),
        _relationship(
            "rel_sharepoint_editor_payroll_site",
            "role_grant",
            "role_sharepoint_editor",
            "res_sharepoint_payroll",
            "Edit on Payroll Collaboration Site",
            "The SharePoint payroll role grants collaborative edit rights on the site.",
            permissions=["Read", "Edit", "Share"],
        ),
        _relationship(
            "rel_mailbox_full_payroll_mailbox",
            "role_grant",
            "role_m365_mailbox_full",
            "res_mailbox_payroll",
            "Full access on payroll mailbox",
            "The mailbox role grants full read and send-as privileges.",
            permissions=["Read", "SendAs", "FullAccess"],
        ),
        _relationship(
            "rel_azure_contributor_prod_subscription",
            "role_grant",
            "role_azure_contributor",
            "res_azure_prod_subscription",
            "Contributor on Payroll-Prod subscription",
            "The Azure role grants write and deploy permissions across the subscription hierarchy.",
            permissions=["Read", "Write", "Deploy", "RoleAssignments.Read"],
            inherits=True,
        ),
        _relationship(
            "rel_keyvault_officer_payroll_vault",
            "role_grant",
            "role_keyvault_secrets",
            "res_keyvault_payroll",
            "Secret officer on payroll vault",
            "The Key Vault role grants secret read, set and delete across the vault.",
            permissions=["ReadSecret", "SetSecret", "DeleteSecret"],
            inherits=True,
        ),
        _relationship(
            "rel_global_reader_directory",
            "role_grant",
            "role_global_reader",
            "res_global_directory",
            "Read on Entra Global Directory",
            "The directory role grants read-only visibility over tenant objects.",
            permissions=["Directory.Read"],
        ),
        _relationship(
            "rel_finance_share_contains_payroll_folder",
            "contains",
            "res_share_finance",
            "res_folder_payroll",
            "Finance Share contains Payroll Folder",
            "The payroll folder inherits file permissions from the finance share unless broken.",
        ),
        _relationship(
            "rel_subscription_contains_keyvault",
            "contains",
            "res_azure_prod_subscription",
            "res_keyvault_payroll",
            "Subscription contains payroll Key Vault",
            "The payroll vault lives inside the Payroll-Prod Azure subscription.",
        ),
        _relationship(
            "rel_keyvault_contains_secret",
            "contains",
            "res_keyvault_payroll",
            "res_secret_salary_export",
            "Key Vault contains salary export secret",
            "The secret inherits access from the Key Vault scope.",
        ),
    ]

    connectors = [
        ConnectorStatus(
            name="Identity Sync",
            source="Active Directory",
            status="healthy",
            latency_ms=412,
            last_sync="2026-03-13T20:53:00Z",
            coverage="Users, nested groups, baseline entitlements",
        ),
        ConnectorStatus(
            name="Cloud IAM Sync",
            source="Entra ID + Azure RBAC",
            status="healthy",
            latency_ms=589,
            last_sync="2026-03-13T20:56:00Z",
            coverage="Groups, roles, delegated directory access, subscription grants",
        ),
        ConnectorStatus(
            name="Collaboration ACL Sync",
            source="Microsoft 365",
            status="warning",
            latency_ms=1128,
            last_sync="2026-03-13T20:47:00Z",
            coverage="SharePoint site permissions and Exchange shared mailboxes",
        ),
        ConnectorStatus(
            name="Privileged Vault Sync",
            source="CyberArk",
            status="healthy",
            latency_ms=506,
            last_sync="2026-03-13T20:51:00Z",
            coverage="Break-glass groups, emergency responders and PAM assignments",
        ),
        ConnectorStatus(
            name="Graph Cache",
            source="Access Path Engine",
            status="healthy",
            latency_ms=96,
            last_sync="2026-03-13T20:58:00Z",
            coverage="Pre-computed explainable paths for critical resources",
        ),
    ]

    history = [
        HistoricalPoint(day="2026-03-07", privileged_paths=14, dormant_entitlements=6, change_requests=3),
        HistoricalPoint(day="2026-03-08", privileged_paths=15, dormant_entitlements=6, change_requests=2),
        HistoricalPoint(day="2026-03-09", privileged_paths=15, dormant_entitlements=5, change_requests=4),
        HistoricalPoint(day="2026-03-10", privileged_paths=17, dormant_entitlements=5, change_requests=6),
        HistoricalPoint(day="2026-03-11", privileged_paths=18, dormant_entitlements=4, change_requests=5),
        HistoricalPoint(day="2026-03-12", privileged_paths=18, dormant_entitlements=4, change_requests=7),
        HistoricalPoint(day="2026-03-13", privileged_paths=19, dormant_entitlements=4, change_requests=8),
    ]

    insights = [
        InsightNote(
            title="Delegation drift on payroll",
            body="A temporary delegation keeps Omar Diaz on the Payroll Editors path until March 31, 2026.",
            tone="warn",
        ),
        InsightNote(
            title="Cloud blast radius is concentrated",
            body="One Azure role assignment fans out to the subscription, Key Vault and salary export secret.",
            tone="critical",
        ),
        InsightNote(
            title="Support exception is tight but direct",
            body="Paolo Greco only has a direct Read ACL on the finance share plus delegated directory read visibility.",
            tone="good",
        ),
    ]

    return Snapshot(
        tenant="Northwind Payroll",
        generated_at="2026-03-13T20:58:00Z",
        entities=entities,
        relationships=relationships,
        connectors=connectors,
        history=history,
        insights=insights,
    )


def build_scaled_snapshot(scale: int) -> Snapshot:
    if scale <= 1:
        return build_demo_snapshot()

    base = build_demo_snapshot()
    entities = []
    relationships = []

    for index in range(scale):
        suffix = "" if index == 0 else f"_s{index + 1}"
        for entity in base.entities:
            entities.append(
                entity.model_copy(
                    update={
                        "id": f"{entity.id}{suffix}",
                        "name": entity.name if index == 0 else f"{entity.name} [{index + 1}]",
                    }
                )
            )

        for relationship in base.relationships:
            relationships.append(
                relationship.model_copy(
                    update={
                        "id": f"{relationship.id}{suffix}",
                        "source": f"{relationship.source}{suffix}",
                        "target": f"{relationship.target}{suffix}",
                    }
                )
            )

    return base.model_copy(
        update={
            "tenant": f"{base.tenant} x{scale}",
            "entities": entities,
            "relationships": relationships,
        }
    )
