from __future__ import annotations

import re
from collections.abc import Callable

SUPPORTED_REPORT_LOCALES = {"en", "it", "de", "fr", "es"}

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "it": {
        "GrantPath Access Intelligence Report": "Report di GrantPath Access Intelligence",
        "GrantPath": "GrantPath",
        "Access Review Report": "Report di revisione accessi",
        "Operator-grade explainability for identity, group, role, ACL and delegated access review.": (
            "Explainability di livello operativo per identita, gruppi, ruoli, ACL e revisioni di accesso delegate."
        ),
        "Tenant": "Tenant",
        "Principal": "Principale",
        "Resource": "Risorsa",
        "Scenario": "Scenario",
        "Executive Summary": "Sintesi executive",
        "Why This Access Exists": "Perche esiste questo accesso",
        "Access answer": "Risposta di accesso",
        "Effective permissions": "Permessi effettivi",
        "Primary path count": "Numero di percorsi principali",
        "Risk posture": "Postura di rischio",
        "Risk score": "Punteggio di rischio",
        "Scenario edge": "Edge di scenario",
        "Impacted principals": "Principali impattati",
        "Privileged paths removed": "Percorsi privilegiati rimossi",
        "The explanation below ranks the clearest access paths first, then keeps the operational blast radius ready for review or export.": (
            "La spiegazione seguente ordina prima i percorsi di accesso piu chiari e mantiene pronto il blast radius operativo per review o export."
        ),
        "Who Has Access To {resource}": "Chi ha accesso a {resource}",
        "Resource exposure is flattened and pre-ranked for readability, including permission mode and supporting rationale.": (
            "L'esposizione della risorsa viene appiattita e preordinata per la leggibilita, includendo modalita del permesso e motivazione."
        ),
        "Principal Footprint": "Impronta del principale",
        "This section shows where the selected principal still has effective coverage across the current snapshot.": (
            "Questa sezione mostra dove il principale selezionato mantiene ancora copertura effettiva nello snapshot corrente."
        ),
        "What-If Blast Radius": "Blast radius What-If",
        "Official Connector Blueprint": "Blueprint ufficiale dei connettori",
        "Collector coverage is shown exactly as implemented today, so the report stays honest about what is live, partial or blueprint-only.": (
            "La copertura dei collector e mostrata esattamente come implementata oggi, cosi il report resta onesto su cio che e live, partial o blueprint-only."
        ),
        "Generated by GrantPath. Export designed for operational reviews, evidence packages and executive briefings.": (
            "Generato da GrantPath. Export progettato per revisioni operative, pacchetti di evidenza e brief executive."
        ),
        "Metric": "Metrica",
        "Value": "Valore",
        "Delta": "Delta",
        "Permissions": "Permessi",
        "Mode": "Modalita",
        "Paths": "Percorsi",
        "Risk": "Rischio",
        "Why": "Perche",
        "Resource": "Risorsa",
        "Impacted principals": "Principali impattati",
        "Removed permissions": "Permessi rimossi",
        "Severity": "Severita",
        "Vendor": "Vendor",
        "Surface": "Superficie",
        "Implementation": "Implementazione",
        "Freshness": "Freschezza",
        "Summary": "Sintesi",
        "Description": "Descrizione",
        "Commentary": "Commento",
        "Review Campaign": "Campagna di review",
        "Access Review Campaign": "Campagna di revisione accessi",
        "Reviewed access": "Accessi revisionati",
        "Campaign evidence is formatted for auditability: affected identity, target resource, effective permissions, reviewer decision and suggested remediation.": (
            "L'evidenza della campagna e formattata per l'auditabilita: identita impattata, risorsa target, permessi effettivi, decisione del reviewer e remediation suggerita."
        ),
        "Decision": "Decisione",
        "Remediation": "Remediation",
        "Total items": "Elementi totali",
        "Pending": "In attesa",
        "Keep": "Mantieni",
        "Revoke": "Revoca",
        "Follow up": "Follow up",
        "Direct": "Diretto",
        "Inherited": "Ereditato",
        "critical": "critico",
        "warn": "attenzione",
        "good": "buono",
        "live": "live",
        "partial": "parziale",
        "blueprint": "blueprint",
        "snapshot": "snapshot",
        "incremental": "incrementale",
        "hybrid": "ibrido",
    },
    "de": {
        "GrantPath Access Intelligence Report": "GrantPath Access Intelligence Bericht",
        "GrantPath": "GrantPath",
        "Access Review Report": "Zugriffspruefbericht",
        "Why This Access Exists": "Warum dieser Zugriff existiert",
        "Executive Summary": "Management-Zusammenfassung",
        "Principal Footprint": "Prinzipal-Footprint",
        "What-If Blast Radius": "What-If Blast Radius",
        "Official Connector Blueprint": "Offizieller Connector-Blueprint",
        "Reviewed access": "Gepruefter Zugriff",
        "Total items": "Gesamte Eintraege",
        "Pending": "Offen",
        "Keep": "Behalten",
        "Revoke": "Entziehen",
    },
    "fr": {
        "GrantPath Access Intelligence Report": "Rapport GrantPath Access Intelligence",
        "GrantPath": "GrantPath",
        "Access Review Report": "Rapport de revue des acces",
        "Why This Access Exists": "Pourquoi cet acces existe",
        "Executive Summary": "Synthese executive",
        "Principal Footprint": "Empreinte du principal",
        "What-If Blast Radius": "Blast radius What-If",
        "Official Connector Blueprint": "Blueprint officiel des connecteurs",
        "Reviewed access": "Acces revu",
        "Total items": "Elements totaux",
        "Pending": "En attente",
        "Keep": "Conserver",
        "Revoke": "Revoquer",
    },
    "es": {
        "GrantPath Access Intelligence Report": "Informe GrantPath Access Intelligence",
        "GrantPath": "GrantPath",
        "Access Review Report": "Informe de revision de accesos",
        "Why This Access Exists": "Por que existe este acceso",
        "Executive Summary": "Resumen ejecutivo",
        "Principal Footprint": "Huella del principal",
        "What-If Blast Radius": "Blast radius What-If",
        "Official Connector Blueprint": "Blueprint oficial de conectores",
        "Reviewed access": "Acceso revisado",
        "Total items": "Elementos totales",
        "Pending": "Pendiente",
        "Keep": "Mantener",
        "Revoke": "Revocar",
    },
}

_DYNAMIC_RULES: dict[str, list[tuple[re.Pattern[str], Callable[..., str]]]] = {
    "it": [
        (re.compile(r"^(\d+) groups included$"), lambda count: f"{count} gruppi inclusi"),
        (re.compile(r"^(\d+) active collectors$"), lambda count: f"{count} collector attivi"),
        (re.compile(r"^(\d+) delegated$"), lambda count: f"{count} delegati"),
        (re.compile(r"^(\d+) deny entries modeled$"), lambda count: f"{count} deny modellati"),
    ]
}


def normalize_report_locale(value: str | None) -> str:
    locale = (value or "en").strip().lower()
    return locale if locale in SUPPORTED_REPORT_LOCALES else "en"


def tr(locale: str, source: str, **params: object) -> str:
    locale = normalize_report_locale(locale)
    translated = source if locale == "en" else _TRANSLATIONS.get(locale, {}).get(source, source)
    if translated == source and locale != "en":
        for pattern, renderer in _DYNAMIC_RULES.get(locale, []):
            match = pattern.match(source)
            if match:
                translated = renderer(*match.groups())
                break
    for key, value in params.items():
        translated = translated.replace("{" + key + "}", str(value))
    return translated
